version: '2.3'
services:

  magento-test-server:
    image: nginx:1.19
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/var/www/html
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - magento-test-php

  magento-test-php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - .:/var/www/html
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./docker/php/mods/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
    links:
      - magento-test-db
    depends_on:
      - magento-test-db

  magento-test-db:
    container_name: magento-test-db
    image: mysql:5.7
    volumes:
      - "~/.magento-test/db:/var/lib/mysql"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "4306:3306"
      - "3306:3306"

  magento-test-elasticsearch:
    image: elasticsearch:7.9.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
